<?php

/**
 * @info
 * Display logic related to the "site" content type.
 */

/**
 * Implements hook_views_api().
 */
function dwa_site_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'dwa_site') . '/includes/views',
  );
}



/**
 * Implements hook_preprocess_node(&$variables)
 */
function dwa_site_preprocess_node(&$variables) {
  if (isset($variables['type']) && $variables['type'] == 'site') {
    $node = $variables['node'];
    $nid = $node->nid;
    $content = $variables['content'];

    // Override the default node display.    
    $variables['content'] = array();
    
    // Add a container for site meta information at the top.    
    $variables['content']['site_meta_top'] = array(
      '#type' => 'container',
      '#weight' => 0,
      '#attributes' => array(
        'class' => array('site-meta site-meta-top'),
      ),
    );
        
    // Add a link to visit the site.
    $variables['content']['site_meta_top']['site_link'] = array(
      '#type' => 'link',
      '#title' => t('Visit Site'),
      '#href' => $node->field_site_link['und'][0]['url'],
      '#prefix' => '<div id="site-link">',
      '#suffix' => '</div>',
      '#attributes' => array(
        'target' => array('_blank'),
      ),
      '#weight' => 1,
    );
    
    // Add the slideshow for this site.
    $variables['content'][] = array(
      '#markup' => views_embed_view('site_slideshow', 'default', $node->nid),
      '#weight' => 2,
    );
    
    // Add a container for site meta information at the bottom.
    $variables['content']['site_meta_bottom'] = array(
      '#type' => 'container',
      '#weight' => 4,
      '#attributes' => array(
        'class' => array('site-meta site-meta-bottom'),
      ),
    );
    
    $variables['content']['site_meta_bottom']['description'] = array(
      '#type' => 'markup',
      '#markup' => $node->body['und'][0]['safe_value'],
      '#prefix' => '<div id="site-meta-description">',
      '#suffix' => '</div>',
      '#weight' => 3,
    );
    
    $variables['content']['site_meta_bottom']['site_link_1'] = array(
      '#type' => 'link',
      '#title' => t('Visit Site'),
      '#href' => $node->field_site_link['und'][0]['url'],
      '#prefix' => '<div id="site-link">',
      '#suffix' => '</div>',
      '#attributes' => array(
        'target' => array('_blank'),
      ),
      '#weight' => 1,
    );     
    
  }
}