<?php

/**
 * @file
 * API functionality for DWA.
 */

function dwa_api_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'dwa_api') . '/includes/views',
  );
}


/**
 * Implements hook_block_info().
 */
function dwa_api_block_info() {
  $blocks = array();
  
  $blocks['copyright'] = array(
    'info' => t('DWA Copyright'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function dwa_api_block_view($block_name = '') {
  switch ($block_name) {
    case 'copyright':
//      $content = theme('item_list', $theme_args);
      $content = 'Drupal Website Awards';    
      $block = array(
        'content' => $content,
      );
      
      return $block;
  }
}



/**
 * Implements hook_image_default_styles().
 */
function dwa_api_image_default_styles() {
  $styles = array();

  $styles['site-screenshot'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale', 
        'data' => array(
          'width' => 680,
          'height' => null,
          'upscale' => 0,
        ),
        'weight' => 1,
      ),
      array(
        'name' => 'image_crop', 
        'data' => array(
          'width' => 680,
          'height' => 435,
          'anchor' => 'left-top',
        ),
        'weight' => 2,
      ),
    ),
  );
  
  $styles['site-thumb'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale', 
        'data' => array(
          'width' => 155,
          'height' => null,
          'upscale' => 0,
        ),
        'weight' => 1,
      ),
      array(
        'name' => 'image_crop', 
        'data' => array(
          'width' => 155,
          'height' => 100,
          'anchor' => 'left-top',
        ),
        'weight' => 2,
      ),
    ),
  );  

  return $styles;
}