<?php

/**
 * @file
 * Provides voting logic for Favorite Website Awards.
 */
define('DWA_VOTING_AWARD_ID_SOD', 1);
define('DWA_VOTING_AWARD_ID_SOW', 2);
define('DWA_VOTING_AWARD_ID_SOM', 3);
define('DWA_VOTING_AWARD_NAME_SOD', t('Site of the Day'));
define('DWA_VOTING_AWARD_NAME_SOW', t('Site of the Week'));
define('DWA_VOTING_AWARD_NAME_SOM', t('Site of the Month'));
define('DWA_VOTING_FID_SOD', variable_get('dwa_voting_fid_sod', 5));
define('DWA_VOTING_FID_SOW', variable_get('dwa_voting_fid_sod', 6));
define('DWA_VOTING_FID_SOM', variable_get('dwa_voting_fid_sod', 7));

/**
 * Implements hook_block_info().
 */
function dwa_voting_block_info() {
  $blocks = array();
  
  $blocks['voting'] = array(
    'info' => t('Site Voting'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function dwa_voting_block_view($block_name = '') {
  switch ($block_name) {
    case 'voting':
      // Don't show this block on non-site nodes.
      if (arg(0) == 'node' && is_numeric(arg(1))) {
        $node = node_load(arg(1));
        if ($node->type != 'site') {
          return false;        
        }
      }
      else {
        return false;
      }
      
      // Determine node content.
      $block = array(
        'subject' => t('Vote for this Site'),
        'content' => dwa_voting_block_content($node),
      );
      
      return $block;
  }
}



/**
 * Implements hook_flag_default_flags().
 */
function dwa_voting_flag_default_flags() {
  $flags = array();
  
  // Exported flag: "Site of the Day".
  $flags['sod'] = array (
    'content_type' => 'node',
    'title' => 'Site of the Day',
    'global' => '0',
    'types' => 
    array (
      0 => 'site',
    ),
    'flag_short' => 'Vote "Site of the Day"',
    'flag_long' => 'Vote this site for the "Site of the Day" award',
    'flag_message' => 'Voted as "Site of the Day"',
    'unflag_short' => 'Remove your vote for "Site of the Day"',
    'unflag_long' => 'Remove your vote for the "Site of the Day" award',
    'unflag_message' => 'Un-Voted as "Site of the Day"',
    'unflag_denied_text' => 'You cannot change your vote for "Site of the Day"',
    'link_type' => 'normal',
    'roles' => 
    array (
      'flag' => 
      array (
        0 => '2',
      ),
      'unflag' => 
      array (
      ),
    ),
    'show_on_page' => 1,
    'show_on_teaser' => 0,
    'show_on_form' => 0,
    'access_author' => '',
    'i18n' => 0,
    'api_version' => 2,
  );
  
  // Exported flag: "Site of the Week".
  $flags['sow'] = array (
    'content_type' => 'node',
    'title' => 'Site of the Week',
    'global' => '0',
    'types' => 
    array (
      0 => 'site',
    ),
    'flag_short' => 'Vote "Site of the Week"',
    'flag_long' => 'Vote this site for the "Site of the Week" award',
    'flag_message' => 'Votes as "Site of the Week"',
    'unflag_short' => 'Remove your vote for "Site of the Week"',
    'unflag_long' => 'Remove your vote for the "Site of the Week" award',
    'unflag_message' => 'Un-Voted as "Site of the Month"',
    'unflag_denied_text' => 'You cannot change your vote for "Site of the Week"',
    'link_type' => 'toggle',
    'roles' => 
    array (
      'flag' => 
      array (
        0 => '2',
      ),
      'unflag' => 
      array (
      ),
    ),
    'show_on_page' => 1,
    'show_on_teaser' => 0,
    'show_on_form' => 0,
    'access_author' => '',
    'i18n' => 0,
    'api_version' => 2,
  );
  
  // Exported flag: "Site of the Month".
  $flags['som'] = array (
    'content_type' => 'node',
    'title' => 'Site of the Month',
    'global' => '0',
    'types' => 
    array (
      0 => 'site',
    ),
    'flag_short' => 'Vote "Site of the Month"',
    'flag_long' => 'Vote this site for the "Site of the Month" award',
    'flag_message' => 'Voted as "Site of the Month"',
    'unflag_short' => 'Remove your vote for "Site of the Month"',
    'unflag_long' => 'Remove your vote for the "Site of the Month" award',
    'unflag_message' => 'Un-Voted as "Site of the Month"',
    'unflag_denied_text' => 'You cannot change your vote for "Site of the Month"',
    'link_type' => 'toggle',
    'roles' => 
    array (
      'flag' => 
      array (
        0 => '2',
      ),
      'unflag' => 
      array (
      ),
    ),
    'show_on_page' => 1,
    'show_on_teaser' => 0,
    'show_on_form' => 0,
    'access_author' => '',
    'i18n' => 0,
    'api_version' => 2,
  );
  
  return $flags;  
}



/**
 * Prepare content for site voting block.
 *
 * @params $node
 *   Site Node.
 *
 * @return
 *   Themed content.
 */
function dwa_voting_block_content($node) {
  // Determine if the current user has cast a vote for this site.
  $votes_node = dwa_voting_get_user_site_votes($node->nid, $GLOBALS['user']->uid);
  
  // Determine if the user can vote again.
  $votes_last = dwa_voting_get_last_user_votes($GLOBALS['user']->uid);

  $data = array();
  
  // Display a flag link for sod if:
  // - This site hasn't already been voted for sod
  // - The user has not already voted for this site
  // - The user can still vote for sod today
  $data[] = t('Site of the Day');
  if (isset($node->field_site_award_day['und']['0']['value'])) {
    $data[] = t('This site has already been voted "Site of the Day" on !date', array('!date' => format_date($node->field_site_award_day['und']['0']['value'], 'custom', 'F j, Y')));
  }
  else if (isset($votes_node[1])) {
    $data[] = t('You already voted this site for "Site of the Day" on !date', array('!date' => format_date($votes_node[1]['timestamp'], 'custom', 'F j, Y')));
  }
  else if ($votes_last[1]['voteable'] === false) {
    $data[] = t('You already voted this site for "Site of the Day" on !date', array('!date' => format_date($votes_last[1]['timestamp'], 'custom', 'F j, Y')));
  }

  return implode("<br />", $data);
  
  $data = array();
  // Add information about the votes this user has cast for this site.
  if (!empty($votes_node)) {
    foreach ($votes_node as $vote) {
      $replacements = array(
        '!award_name' => _dwa_voting_award_name($vote['award_id']),
        '!date' => format_date($vote['timestamp'], 'custom', 'F j'),
      );
      $data['award' . $vote['award_id']] = t('You already voted this site for "!award_name" on !date', $replacements);
    }
  }
  
  return implode("<br />", $data);
}



/**
 * Determine the last time a user has voted on all available types.
 * 
 * @param $uid
 *   User ID, defaults to current user.
 * 
 * @return
 *   Array of last votes.
 */
function dwa_voting_get_last_user_votes($uid) {
  if (!isset($uid)) {
    $uid = $GLOBALS['user']->uid;
  }
    
  $votes = array();
  $flag_ids = array(DWA_VOTING_FID_SOD, DWA_VOTING_FID_SOW, DWA_VOTING_FID_SOM);
  foreach ($flag_ids as $flag_id) {
    $query = db_select('flag_content', 'fc');
    $query->fields('fc');
    $query->condition('fc.uid', $uid);
    $query->condition('fc.fid', $flag_id);
    $query->range(0, 1);
    $query->orderBy('timestamp', 'DESC');
    $result = $query->execute();
    $record = $result->fetchObject();
    $award_id = _dwa_voting_map_flag_award($flag_id);    
    if (is_object($record)) {
      $votes[$award_id] = array(
        'award_id' => $award_id,
        'timestamp' => $record->timestamp,
        'site_nid' => $record->content_id,
      );
    }
    else {
      $votes[$award_id] = array();
    }
  }
 
  // Every user has 1 vote per award type per day.
  // Add additional information for each vote.
  // 1. Boolean Indicator if user can vote for this award
  // 2. Duration until next vote is allowed.
  foreach ($votes as $id => $vote) {
    // If the user has never voted before or
    // the last vote for this award was yesterday,
    // the user can vote again.
    if (empty($vote) || (isset($vote['timestamp']) && ($vote['timestamp'] < strtotime("today")))) {
      $votes[$id]['wait'] = 0;
      $votes[$id]['voteable'] = true;
    }
    // If the user has voted for this award today,
    // calculate the duration until he can vote again.
    else {
      $votes[$id]['wait'] = strtotime("tomorrow") - $vote['timestamp'];
      $votes[$id]['voteable'] = false;
    }
  }
  
  return $votes;
}



/**
 * Determine the votes of the current user for this site.
 *
 * @param $nid
 *   Node ID.
 * @param $uid
 *   Uid, defaults to current user.
 *
 * @return
 *   Array of votes.
 */
function dwa_voting_get_user_site_votes($nid, $uid) {
  if (!isset($nid)) {
    return false;
  }
  
  if (!isset($uid)) {
    $uid = $GLOBALS['user']->uid;    
  }
  
  $votes = array();
  $query = db_select('flag_content', 'fc');
  $query->fields('fc');
  $query->condition('fc.content_id', $nid);
  $query->condition('fc.uid', $uid);  
  $query->condition('fc.fid', array(DWA_VOTING_FID_SOD, DWA_VOTING_FID_SOW, DWA_VOTING_FID_SOM), 'IN');
  $result = $query->execute();
  
  foreach ($result as $record) {
    $award_id = _dwa_voting_map_flag_award($record->fid);
    $votes[$award_id] = array(
      'award_id' => $award_id,
      'timestamp' => $record->timestamp,
    );
  }
  
  return $votes;  
}



/**
 * Helper function to map flag ids to award ids.
 *
 * @param $flag_id
 *   Flag ID.
 *
 * @return
 *   Award ID.
 */
function _dwa_voting_map_flag_award($flag_id) {
  if (!isset($flag_id)) {
    return false;
  }
  
  $award_flag_map = array(
    DWA_VOTING_FID_SOD => DWA_VOTING_AWARD_ID_SOD,
    DWA_VOTING_FID_SOW => DWA_VOTING_AWARD_ID_SOW,
    DWA_VOTING_FID_SOM => DWA_VOTING_AWARD_ID_SOM,            
  );

  return $award_flag_map[$flag_id];
}



/**
 * Helper function: Return the name of an award.
 */
function _dwa_voting_award_name($award_id) {
  if (!isset($award_id)) {
    return false;
  }
  
  switch ($award_id) {
     case 1:  $award_name = DWA_VOTING_AWARD_NAME_SOD; break;
     case 2:  $award_name = DWA_VOTING_AWARD_NAME_SOW; break;
     case 3:  $award_name = DWA_VOTING_AWARD_NAME_SOM; break;
     default: $award_name = "Award";
  }
  
  return $award_name;
}
